routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('home', function(){ 
    return redirect()->route('dashboard'); 
});
Route::group(['middleware' => ['auth'], 'prefix' => 'dashboard' ], function(){

    Route::middleware('check-period')->group(function(){
        Route::get('/', 'HomeController@index')->name('dashboard');
        Route::resource('measures', 'MeasureController');
        Route::resource('presentations', 'PresentationController');
        Route::resource('items', 'ItemController');
    });
    
    Route::resource('periods', 'PeriodController');

});

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\ItemPresentation;

class Item extends Model
{

    use SoftDeletes;
    protected $fillable = [
        'item', 'item_code'
    ];

    public function presentations()
    {
        return $this->hasMany(\App\ItemPresentation::class);
    }


    public function syncPresentations(array $presentations)
    {
        $this->presentations->each(function($presentation){
            if( $presentation->dispatches->isEmpty() ) $presentation->delete();
        });

        collect( $presentations )->each(function($item, $index){
            $this->presentations()->save(
                new ItemPresentation([ 'presentation_id' => $item ])
            );
        });


        return $this;
    }
    
    public function hasPresentation(int $id)
    {
        $has = $this->presentations->search(function($presentation) use(&$id){
            return $presentation->presentation_id == $id;
        });

        return $has;
    }


    public function hasDispatches()
    {
        $has = $this->presentations->search( function($presentation){
            return !$presentation->dispatches->isEmpty();
        });


        return $has;
    }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Item;
use App\Presentation;
use Illuminate\Http\Request;
use DB;
use Validator;
class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Item::all();
        $presentations = Presentation::all();
        return view('werehouses.items.index', compact('items', 'presentations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validation = Validator::make($request->all(), [
            'item_code'     => 'required|unique:items,item_code',
            'item'          => 'required',
            'presentations' => 'required|array'
        ], [
            'item_code.required'    => 'Codigo de item no ingresado o incorrecto',
            'item_code.unique'      => 'El codigo que trata de ingresar para el item, ya existe',
            'presentations.required'=> 'El item debe contener presentacions / empaques en los que sera almacenado',
            'item.required'         => 'El item debe contener un nombre valido'
        ]);

        if( $validation->fails() ) return redirect()->back()->withErrors($validation->errors());

        $endTransaction = DB::transaction(function() use(&$request){
            $item = Item::create( $request->except(['presentations']) );
            
            if( $request->has('presentations') )
                $item->syncPresentations( $request->presentations );
            
            return $item;
        });


        return redirect()->back()->with('success', 'El nuevo item ha sido agregado correctamente');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function show(Item $item)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function edit(Item $item)
    {
        $presentations = Presentation::all();
        return view('werehouses.items.edit', compact('presentations', 'item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Item $item)
    {

        return DB::transaction(function() use(&$item, &$request){

            if( $request->item_code != $item->item_code )
            {
                $existCode = Item::whereItemCode( $request->item_code )->first();
                if( !is_null( $existCode ) ) return redirect()->back()->withErrors([
                    'item_code' => [
                        'El codigo que intenta agregar al item ya esta siendo usado por otro, no puede haber dualidad'
                    ]
                ]);
            }
    
            $item->fill($request->only(['item', 'item_code']));
            $item->save();
            $item->syncPresentations( $request->presentations );

            return redirect()->route('items.index')->with('success', 'Datos del item actualizados correctamente');
        });

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function destroy(Item $item)
    {
        if( !is_bool( $item->hasDispatches() ) ) 
            return redirect()->route('items.index')->withErrors([
                'item_dispatches'   => [
                    'No se puede eliminar este item, ya posee un historial de despachos'
                ]
            ]);
        
        $item->delete();
        return redirect()->route('items.index')->with('success', 'El item ha sido removido del sistema correctamente');
    }
}

resources/views/werehouses/items/edit.blade.php
@extends('layouts.app')

@section('area-title', 'Unidades de medida')

@push('css')
    
<link rel="stylesheet" href="{{ asset('assets/styles/vendor/perfect-scrollbar.css') }}">
<link rel="stylesheet" href="{{ asset('assets/styles/vendor/datatables.min.css') }}">
@endpush

@section('content')
<div class="row">
    <div class="col-12">
        <form action="{{ route('items.update', $item) }}" method="POST">
            @csrf
            @method('PUT')
            <div class="col-12">
                <label for="" class="control-label">Item</label>
                <input type="text" value="{{ $item->item }}" placeholder="Nombre del item" class="form-control" name="item" required="required">
            </div>
            <div class="col-12">
                <label for="" class="control-label">Codigo del item</label>
                <input type="text" value="{{ $item->item_code }}" class="form-control" name="item_code" id="item_code">
            </div>
            <div class="col-12">
                <label for="">Presentaciones</label>
                <select name="presentations[]" id="presentations" multiple class="form-control" required="required">
                    @foreach ($presentations as $presentation)
                        <option {{ is_bool( $item->hasPresentation($presentation->id) ) ? 'selected' : '' }} value="{{ $presentation->id }}">
                            {{ $presentation->presentation }} / {{ $presentation->weight }}  {{ $presentation->unit->measure }}
                        </option>
                    @endforeach
                </select>
            </div>
            <div class="row mt-2">
                <div class="col-sm-12">
                    <button type="submit" class="btn btn-success btn-block">Guardar</button>
                </div>
            </div>
        </form>
    </div>
</div>

@endsection

@push('js')
    <script src="{{ asset('assets/js/vendor/perfect-scrollbar.min.js') }}"></script>

    <!-- page vendor js -->
    <script src="{{ asset('assets/js/vendor/datatables.min.js') }}"></script>
    <script src="{{ asset('assets/js/datatables.script.js') }}"></script>
    <script src="{{ asset('assets/js/es5/script.min.js') }}"></script>
    <script src="{{ asset('assets/js/es5/sidebar.large.script.min.js') }}"></script>

    <script src="{{ asset('assets/js/modal.script.js') }}"></script>
@endpush

resources/views/werehouses/items/index.blade.php
@extends('layouts.app')

@section('area-title', 'Unidades de medida')

@push('css')
    
<link rel="stylesheet" href="{{ asset('assets/styles/vendor/perfect-scrollbar.css') }}">
<link rel="stylesheet" href="{{ asset('assets/styles/vendor/datatables.min.css') }}">
@endpush

@section('content')
<div class="row">

    <div class="col-md-5 col-sm-12 col-lg-5 text-right offset-md-7 offset-lg-7">
        <button type="button" class="btn btn-primary m-1" data-toggle="modal" data-target="#itemModalContent" data-whatever="@create">
            Agregar
        </button>
    </div>

</div>
<div class="table-responsive">
    <table id="scroll_vertical_table" class="display table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>ID</th>
                <th>Codigo</th>
                <th>Item</th>
                <th>Presentciones</th>
                <th>Opciones</th>
            </tr>
        </thead>
        <tbody>

            @foreach ($items as $item)
                <tr>
                    <td>{{ $item->id }}</td>
                    <td>{{ $item->item }}</td>
                    <td>{{ $item->item_code }}</td>
                    <td>
                        @foreach ($item->presentations as $presentation)
                            <span class="badge badge-pill badge-outline-primary p-2 m-1">
                                    {{ $presentation->presentation->presentation }} de {{ $presentation->presentation->weight }} {{ $presentation->presentation->unit->measure }}
                            </span>
                            
                        @endforeach
                    </td>
                    <td>
                        <a 
                            class="btn btn-success" 
                            href="{{ route('items.edit', $item) }}"
                        >
                            Editar
                        </a>
                        <button 
                            class="btn btn-danger delete-btn"  
                            data-measure-id="{{ $item->id }}"    
                        >
                            Eliminar
                        </button>
                        <form action="{{ route('items.destroy', $item) }}" id="delete-measure-{{ $item->id }}" method="POST">
                            @csrf
                            @method('DELETE')
                        </form>
                    </td>
                </tr>
            @endforeach

        </tbody>
        <tfoot>
            <tr>
                <th>ID</th>
                <th>Codigo</th>
                <th>Item</th>
                <th>Presentciones</th>
                <th>Opciones</th>
            </tr>
        </tfoot>
    </table>
</div>
<div class="modal fade" id="itemModalContent" tabindex="-1" role="dialog" aria-labelledby="verifyModalContent" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="itemModalContent_title">Nuevo item</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{ route('items.store') }}" method="POST" id="measure-form">
                    @csrf
                    <input type="hidden" name="_method" id="_method" value="POST">
                    <div class="form-group">
                        <label for="recipient-name-2" class="col-form-label">Item</label>
                        <input type="text" placeholder="Unidad del" class="form-control" required name="item" id="item">
                    </div>
                    <div class="form-group">
                        <label for="message-text-1" class="col-form-label">Codigo</label>
                        <input type="text" name="item_code" required placeholder="Codigo de barra / identificación" class="form-control" id="item_code">
                    </div>
                    <div class="form-group">
                        <label for="presentations">Presentaciones / empaques</label>
                        <select name="presentations[]" id="presentations" required multiple class="form-control">
                            @foreach ($presentations as $presentation)
                                <option value="{{ $presentation->id }}">{{ $presentation->presentation }} / {{ $presentation->weight }} {{ $presentation->unit->measure }}</option>
                            @endforeach
                        </select>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                <button type="button" id="save" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </div>
</div>

@endsection

@push('js')
    <script src="{{ asset('assets/js/vendor/perfect-scrollbar.min.js') }}"></script>

    <!-- page vendor js -->
    <script src="{{ asset('assets/js/vendor/datatables.min.js') }}"></script>
    <script src="{{ asset('assets/js/datatables.script.js') }}"></script>
    <script src="{{ asset('assets/js/es5/script.min.js') }}"></script>
    <script src="{{ asset('assets/js/es5/sidebar.large.script.min.js') }}"></script>

    <script src="{{ asset('assets/js/modal.script.js') }}"></script>
@endpush